version: "3.9"

services:
  # server:
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  postgres:
    image: postgres
    ports:
      - "5555:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
